name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install koyeb cli
        uses: koyeb-community/install-koyeb-cli@main
        with:
          token: ${{ secrets.KOYEB_TOKEN }}
      - name: Login to docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: docker build -t bchatelard/abc .
      - name: Docker push
        run: docker push bchatelard/abc
      - name: Update new revision
        run: koyeb get all
