name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STACK_NAME: okay-division
      IMAGE: bchatelard/abc:${{github.sha}}

    steps:
      - uses: actions/checkout@v2
      - name: Install koyeb cli
        uses: koyeb-community/install-koyeb-cli@v1
        with:
          api_key: "${{ secrets.KOYEB_TOKEN }}"
      - name: Login to docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: docker build -t $IMAGE .
      - name: Docker publish new image
        run: docker push $IMAGE
      - name: Generate koyeb.yaml from template
        run: |
          sed "s|{{image}}|$IMAGE|g" koyeb.yaml.tpl > koyeb.yaml
      - name: Update new revision
        run: koyeb create revision $STACK_NAME -f koyeb.yaml
